### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by cyberpsychooo** [hash3liZer/SillyRAT#20]
' File "/home/kali/SillyRAT/server.py", line 13, in <module>
    import PyInstaller.__main__
ModuleNotFoundError: No module named 'PyInstaller'

**Comment by Wijnen01** [comment]
pip3 install Pyinstaller

**Comment by Omicron166** [comment]
> pip3 install Pyinstaller

no, it's pip3 install pyinstaller

**Comment by hash3liZer** [comment]
Hi, @cyberpsychooo , make sure to run this command before running the application: 

```bash
$ pip3 install -r requirements.txt
```

**Comment by Omicron166** [comment]
Also, i found that the latest pyinstaller versión don't have the import
