### ISSUE TITLE
How to compile the client ?

### ISSUE THREAD

**Issue by r3dt3am** [hash3liZer/SillyRAT#7]
I know this is too basic, but how is the client to be compiled ?

**Comment by hash3liZer** [comment]
Hey, the client part is under development. We have yet a basic infrastructure in C++. But we are porting it to Python (Client) for the sake of simplicity and the total usage. All the documentation will be released as soon as the client gets completed.

**Comment by hash3liZer** [comment]
@r3dt3am I've updated the tool, ported it totally to Python.
